# run with pandocomatic -c config.yaml -i input -o docs
settings:
    skip: ["_*"]
    follow-links: true
templates:
    word:
        glob: ["*.md"]
        pandoc:
            to: docx
            use-extension: docx
            reference-doc: templates/jamovi-worksheets.docx
    web:
        glob: ["*.md"]
        pandoc:
            to: html
            standalone: true
            self-contained: true
            toc: true
            template: templates/GitHub.html5
