# run with pandocomatic -i input -o docs -c config.yaml --modified-only
settings:
    skip: ["_*", ".*"]
    recursive: true
    follow-links: false
    match-files: all
templates:
    worksheet-word:
        glob: ["*.md"]
        pandoc:
            from: markdown+raw_attribute+raw_tex
            to: docx
            use-extension: docx
            reference-doc: ./../../templates/jamovi-worksheets.docx
            lua-filter: filters/shortcodes.lua
            #toc: true
    worksheet-html:
        glob: ["*.md"]
        pandoc:
            from: markdown+raw_attribute+raw_tex
            to: html
            standalone: true
            self-contained: true
            toc: true
            template: ./../../templates/jamovi-worksheets.html5
            lua-filter: filters/shortcodes.lua
    worksheet-github:
        glob: ["*.md"]
        extends: ['worksheet-html']
        pandoc:
            output: index.html
    index:
        glob: ["index.txt"]
        pandoc:
            from: markdown+raw_attribute+raw_tex
            to: html
            standalone: true
            self-contained: true
            template: ./../../templates/jamovi-worksheets.html5
            lua-filter: filters/shortcodes.lua
    worksheet-pdf:
        glob: ["*.md"]
        pandoc:
            from: markdown+raw_attribute+raw_tex
            to: pdf
            standalone: true
            self-contained: true
            pdf-engine: lualatex
            metadata-file: ./../../templates/jamovi-worksheets.yaml
            template: ./../../templates/jamovi-worksheets.tex
            lua-filter: filters/shortcodes.lua
